name: pokeapi
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_annotation: ^4.9.0
  dio: ^5.4.3+1
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  mobx_codegen: ^2.6.1
  dartz: ^0.10.1
  logging: ^1.2.0
  get_it: ^7.6.7
  flutter_launcher_icons: ^0.13.1
  cached_network_image: ^3.3.1
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  image_path: "assets/icon.png" 
  android: true
  ios: true
  remove_alpha_ios: true